### PR TITLE
0 6 1 fixes

### LINKED ISSUE #416: "Manage Wallets" missing in some configurations
The section to add/remove/manage wallets is not being displayed in the sidebar.

### PR DESCRIPTION
**Pull request by dafuga**
- Fixes issues #414 and #385.
- Attempts to fix #416 although I am not 100% sure that it fixes the issue that you encountered.
- Also now allows you to stake amounts that had been unstaked but are not yet part of your liquid balance.

### CODE REVIEW

File: app/shared/containers/Tools.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ const paneMapping = [
   },
   {
     element: ToolsWallets,
-    modes: ['cold', 'hot', 'ledger', 'watch'],
+    modes: ['cold', 'hot', 'ledger', 'watch', 'skip'],
```
Comment (dafuga) [inline app/shared/containers/Tools.js]: @aaroncox could it be that you had skipped the setup the one time that the "Manage Wallets" section was hidden for you? Maybe that should show up in the sidebar even when the setup was skipped?

Comment (aaroncox) [reply app/shared/containers/Tools.js]: Could be! We can def test to see if this resolves it
